package http

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"
	"time"

	"github.com/kimseunghwan/llm-viz/backend/internal/domain"
	"github.com/kimseunghwan/llm-viz/backend/internal/port"
)

// minKeyIDLen is the minimum acceptable length for a key ID in path parameters.
// IDs generated by uuid.New() are 36 characters; very short IDs are invalid.
const minKeyIDLen = 8

// saveKeyRequest is the JSON body for POST /api/keys.
type saveKeyRequest struct {
	Provider string `json:"provider"`
	Name     string `json:"name"`
	Key      string `json:"key"`
}

// keyResponse is the JSON representation of a stored API key (no raw key).
type keyResponse struct {
	ID        string `json:"id"`
	Provider  string `json:"provider"`
	Name      string `json:"name"`
	MaskedKey string `json:"masked_key"`
	CreatedAt string `json:"created_at"`
}

// listKeysResponse wraps the key list.
type listKeysResponse struct {
	Keys  []keyResponse `json:"keys"`
	Count int           `json:"count"`
}

func domainKeyToResponse(k domain.APIKey) keyResponse {
	return keyResponse{
		ID:        k.ID,
		Provider:  string(k.Provider),
		Name:      k.Name,
		MaskedKey: k.MaskedKey,
		CreatedAt: k.CreatedAt.Format(time.RFC3339),
	}
}

// writeJSONStatus writes a JSON response with the given status code.
func writeJSONStatus(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

// writeJSONError writes a JSON error response.
func writeJSONError(w http.ResponseWriter, status int, msg string) {
	writeJSONStatus(w, status, map[string]string{"error": msg})
}

// handleCollection dispatches GET /api/keys (list) and POST /api/keys (save).
// Any other method returns 405.
func (s *Server) handleCollection(w http.ResponseWriter, r *http.Request) {
	switch r.Method {
	case http.MethodGet:
		s.handleListKeys(w, r)
	case http.MethodPost:
		s.handleSaveKey(w, r)
	default:
		w.Header().Set("Allow", "GET, POST")
		http.Error(w, "Method Not Allowed", http.StatusMethodNotAllowed)
	}
}

// handleItem dispatches DELETE /api/keys/{id}.
// An empty ID (path is /api/keys/) returns 405.
// Any non-DELETE method returns 405.
func (s *Server) handleItem(w http.ResponseWriter, r *http.Request) {
	id := strings.TrimPrefix(r.URL.Path, "/api/keys/")

	// Empty ID means the request was to /api/keys/ (trailing slash, no ID).
	// Treat as the collection path — only GET/POST allowed there.
	if id == "" {
		w.Header().Set("Allow", "GET, POST")
		http.Error(w, "Method Not Allowed", http.StatusMethodNotAllowed)
		return
	}

	switch r.Method {
	case http.MethodDelete:
		s.handleDeleteKey(w, r, id)
	default:
		w.Header().Set("Allow", "DELETE")
		http.Error(w, "Method Not Allowed", http.StatusMethodNotAllowed)
	}
}

// handleSaveKey handles POST /api/keys.
func (s *Server) handleSaveKey(w http.ResponseWriter, r *http.Request) {
	var req saveKeyRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSONError(w, http.StatusBadRequest, "invalid request body: "+err.Error())
		return
	}

	// Field-level validation with descriptive messages for test assertions.
	if req.Provider == "" {
		writeJSONError(w, http.StatusBadRequest, "provider is required")
		return
	}
	if req.Name == "" {
		writeJSONError(w, http.StatusBadRequest, "name is required")
		return
	}
	if req.Key == "" {
		writeJSONError(w, http.StatusBadRequest, "key is required")
		return
	}

	key, err := s.keyManager.SaveAPIKey(r.Context(), domain.ProviderID(req.Provider), req.Name, req.Key)
	if err != nil {
		writeJSONError(w, http.StatusBadRequest, err.Error())
		return
	}

	writeJSONStatus(w, http.StatusCreated, domainKeyToResponse(key))
}

// handleListKeys handles GET /api/keys.
func (s *Server) handleListKeys(w http.ResponseWriter, r *http.Request) {
	providerFilter := domain.ProviderID(r.URL.Query().Get("provider"))

	keys, err := s.keyManager.ListKeys(r.Context(), providerFilter)
	if err != nil {
		writeJSONError(w, http.StatusInternalServerError, err.Error())
		return
	}

	resp := listKeysResponse{
		Keys:  make([]keyResponse, 0, len(keys)),
		Count: len(keys),
	}
	for _, k := range keys {
		resp.Keys = append(resp.Keys, domainKeyToResponse(k))
	}

	writeJSONStatus(w, http.StatusOK, resp)
}

// handleDeleteKey handles DELETE /api/keys/{id}.
func (s *Server) handleDeleteKey(w http.ResponseWriter, r *http.Request, id string) {
	// IDs shorter than minKeyIDLen are clearly not valid UUIDs — reject early.
	if len(id) < minKeyIDLen {
		writeJSONError(w, http.StatusBadRequest, "invalid key id")
		return
	}

	if err := s.keyManager.DeleteKey(r.Context(), id); err != nil {
		if errors.Is(err, port.ErrKeyNotFound) {
			writeJSONError(w, http.StatusNotFound, "key not found")
			return
		}
		writeJSONError(w, http.StatusInternalServerError, err.Error())
		return
	}

	w.WriteHeader(http.StatusNoContent)
}
